"""init

Revision ID: 36db0764240d
Revises: edace0edb58d
Create Date: 2019-07-23 22:02:31.435339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36db0764240d'
down_revision = 'edace0edb58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FTIRModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('magic', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_FTIRModel_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_FTIRModel')),
    sa.UniqueConstraint('name', name=op.f('uq_FTIRModel_name'))
    )
    op.drop_index('uq_Spectra_detail_index', table_name='spectra_detail')
    op.drop_table('spectra_detail')
    op.drop_table('graph_experiment')
    op.drop_index('uq_FTIRModel_name', table_name='ftirmodel')
    op.drop_table('ftirmodel')
    op.alter_column('publication', 'author',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('publication', 'publication_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication', 'publication_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('publication', 'author',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_table('ftirmodel',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('data', mysql.TEXT(), nullable=False),
    sa.Column('magic', mysql.TEXT(), nullable=False),
    sa.Column('creator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='fk_FTIRModel_creator_id_users'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_FTIRModel_name', 'ftirmodel', ['name'], unique=True)
    op.create_table('graph_experiment',
    sa.Column('spectra_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('a', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('b', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('c', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('d', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('spectra_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('spectra_detail',
    sa.Column('spectra_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('spectra_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_Spectra_detail_index', 'spectra_detail', ['index'], unique=True)
    op.drop_table('FTIRModel')
    # ### end Alembic commands ###
